2022-05-17 22:37:54 INFO  [main]: Faulty itemID entry.
2022-05-17 22:37:59 INFO  [main]: No Item Found.
2022-05-17 22:38:02 ERROR [main]: No suitable driver found for jdbc:mysql://localhost/noConnectionTest
2022-05-17 23:00:37 ERROR [main]: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
2022-05-18 11:16:55 ERROR [main]: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
2022-05-18 11:18:24 INFO  [main]: No Item Found.
2022-05-18 11:37:32 WARN  [main]: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
2022-05-18 11:37:32 WARN  [main]: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
2022-05-18 11:37:34 INFO  [main]: No Item Found.
2022-05-18 11:37:34 INFO  [main]: No Item Found.
2022-05-19 00:42:07 INFO  [main]: Payment must be provided
2022-05-19 12:57:48 INFO  [main]: No Item Found.
2022-05-19 13:04:02 INFO  [main]: No Item Found.
2022-05-27 15:54:47 WARN  [main]: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at java.sql.DriverManager.getConnection(DriverManager.java:681) ~[java.sql:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:229) ~[java.sql:?]
	at se.kth.iv1350.saleSystem.integration.ItemCatalog.connectToDB(ItemCatalog.java:52) ~[classes/:?]
	at se.kth.iv1350.saleSystem.integration.ItemCatalog.searchForItem(ItemCatalog.java:38) ~[classes/:?]
	at se.kth.iv1350.saleSystem.model.Sale.addItem(Sale.java:41) ~[classes/:?]
	at se.kth.iv1350.saleSystem.controller.Controller.enterItem(Controller.java:51) ~[classes/:?]
	at se.kth.iv1350.saleSystem.view.View.runView(View.java:49) ~[classes/:?]
	at se.kth.iv1350.saleSystem.Startup.Main.main(Main.java:17) ~[classes/:?]
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:120) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:948) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:818) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	... 11 more
Caused by: java.net.ConnectException: Connection refused: connect
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:579) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:568) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:633) ~[?:?]
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:153) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:120) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:948) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:818) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	... 11 more
2022-05-27 15:54:47 WARN  [main]: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at java.sql.DriverManager.getConnection(DriverManager.java:681) ~[java.sql:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:229) ~[java.sql:?]
	at se.kth.iv1350.saleSystem.integration.ItemCatalog.connectToDB(ItemCatalog.java:52) ~[classes/:?]
	at se.kth.iv1350.saleSystem.integration.ItemCatalog.searchForItem(ItemCatalog.java:38) ~[classes/:?]
	at se.kth.iv1350.saleSystem.model.Sale.addItem(Sale.java:41) ~[classes/:?]
	at se.kth.iv1350.saleSystem.controller.Controller.enterItem(Controller.java:51) ~[classes/:?]
	at se.kth.iv1350.saleSystem.view.View.runView(View.java:49) ~[classes/:?]
	at se.kth.iv1350.saleSystem.Startup.Main.main(Main.java:17) ~[classes/:?]
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:120) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:948) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:818) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	... 11 more
Caused by: java.net.ConnectException: Connection refused: connect
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:579) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:568) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:633) ~[?:?]
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:153) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:120) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:948) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:818) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	... 11 more
2022-05-27 15:57:46 INFO  [main]: No Item Found.
se.kth.iv1350.saleSystem.exceptions.NoItemFoundException: No Item Found.
	at se.kth.iv1350.saleSystem.integration.ItemCatalog.searchForItem(ItemCatalog.java:43) ~[classes/:?]
	at se.kth.iv1350.saleSystem.model.Sale.addItem(Sale.java:41) ~[classes/:?]
	at se.kth.iv1350.saleSystem.controller.Controller.enterItem(Controller.java:51) ~[classes/:?]
	at se.kth.iv1350.saleSystem.view.View.runView(View.java:49) ~[classes/:?]
	at se.kth.iv1350.saleSystem.Startup.Main.main(Main.java:17) ~[classes/:?]
2022-05-27 15:57:46 INFO  [main]: No Item Found.
se.kth.iv1350.saleSystem.exceptions.NoItemFoundException: No Item Found.
	at se.kth.iv1350.saleSystem.integration.ItemCatalog.searchForItem(ItemCatalog.java:43) ~[classes/:?]
	at se.kth.iv1350.saleSystem.model.Sale.addItem(Sale.java:41) ~[classes/:?]
	at se.kth.iv1350.saleSystem.controller.Controller.enterItem(Controller.java:51) ~[classes/:?]
	at se.kth.iv1350.saleSystem.view.View.runView(View.java:49) ~[classes/:?]
	at se.kth.iv1350.saleSystem.Startup.Main.main(Main.java:17) ~[classes/:?]
2022-05-27 15:57:50 INFO  [main]: Payment can not be negative or zero.
java.lang.IllegalArgumentException: Payment can not be negative or zero.
	at se.kth.iv1350.saleSystem.controller.Controller.enterAmountPaid(Controller.java:87) ~[classes/:?]
	at se.kth.iv1350.saleSystem.view.View.saleEnded(View.java:85) ~[classes/:?]
	at se.kth.iv1350.saleSystem.view.View.runView(View.java:59) ~[classes/:?]
	at se.kth.iv1350.saleSystem.Startup.Main.main(Main.java:17) ~[classes/:?]
2022-05-27 20:02:23 INFO  [main]: No Item Found.
se.kth.iv1350.saleSystem.exceptions.NoItemFoundException: No Item Found.
	at se.kth.iv1350.saleSystem.integration.ItemCatalog.searchForItem(ItemCatalog.java:43) ~[classes/:?]
	at se.kth.iv1350.saleSystem.model.Sale.addItem(Sale.java:41) ~[classes/:?]
	at se.kth.iv1350.saleSystem.controller.Controller.enterItem(Controller.java:51) ~[classes/:?]
	at se.kth.iv1350.saleSystem.view.View.runView(View.java:49) ~[classes/:?]
	at se.kth.iv1350.saleSystem.Startup.Main.main(Main.java:17) ~[classes/:?]
2022-05-27 20:02:23 INFO  [main]: No Item Found.
se.kth.iv1350.saleSystem.exceptions.NoItemFoundException: No Item Found.
	at se.kth.iv1350.saleSystem.integration.ItemCatalog.searchForItem(ItemCatalog.java:43) ~[classes/:?]
	at se.kth.iv1350.saleSystem.model.Sale.addItem(Sale.java:41) ~[classes/:?]
	at se.kth.iv1350.saleSystem.controller.Controller.enterItem(Controller.java:51) ~[classes/:?]
	at se.kth.iv1350.saleSystem.view.View.runView(View.java:49) ~[classes/:?]
	at se.kth.iv1350.saleSystem.Startup.Main.main(Main.java:17) ~[classes/:?]
2022-05-27 20:02:56 DEBUG [main]: se.kth.iv1350.saleSystem.exceptions.InsufficientPaymentException: Payment must cover whole price.
2022-05-27 20:02:56 DEBUG [main]: se.kth.iv1350.saleSystem.exceptions.InsufficientPaymentException: Payment must cover whole price.
2022-05-27 20:02:57 DEBUG [main]: se.kth.iv1350.saleSystem.exceptions.InsufficientPaymentException: Payment must cover whole price.
2022-05-27 20:02:57 DEBUG [main]: se.kth.iv1350.saleSystem.exceptions.InsufficientPaymentException: Payment must cover whole price.
2022-05-27 20:02:57 DEBUG [main]: se.kth.iv1350.saleSystem.exceptions.InsufficientPaymentException: Payment must cover whole price.
2022-05-27 20:02:57 DEBUG [main]: se.kth.iv1350.saleSystem.exceptions.InsufficientPaymentException: Payment must cover whole price.
2022-05-27 20:02:58 INFO  [main]: Payment can not be negative or zero.
java.lang.IllegalArgumentException: Payment can not be negative or zero.
	at se.kth.iv1350.saleSystem.controller.Controller.enterAmountPaid(Controller.java:87) ~[classes/:?]
	at se.kth.iv1350.saleSystem.view.View.saleEnded(View.java:85) ~[classes/:?]
	at se.kth.iv1350.saleSystem.view.View.runView(View.java:59) ~[classes/:?]
	at se.kth.iv1350.saleSystem.Startup.Main.main(Main.java:17) ~[classes/:?]
2022-05-27 20:03:03 DEBUG [main]: se.kth.iv1350.saleSystem.exceptions.InsufficientPaymentException: Payment must cover whole price.
